name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

      - if: matrix.os == 'windows-latest'
        name: Run Cake script Windows
        run: |
          ./build.ps1

      - if: matrix.os != 'windows-latest'
        name: Run Cake script Posix
        run: |
          ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: nuget